[profile.default]
# Sets the concrete solc version to use
# This overrides the `auto_detect_solc` value
solc_version = '0.8.21'
auto_detect_solc = false
evm_version = 'prague'
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./" }]

remappings = [
    "@solmate/=lib/solmate/src/",
    "@forge-std/=lib/forge-std/src/",
    "@ds-test/=lib/forge-std/lib/ds-test/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "@openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@ccip=lib/ccip/",
    "@oapp-auth=lib/OAppAuth/src/",
    "@cryptoalgebra/Algebra=lib/Algebra/src/core/",
    "@layerzerolabs/lz-evm-protocol-v2/=lib/OAppAuth/lib/LayerZero-V2/packages/layerzero-v2/evm/protocol/"
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
polygon = "${MATIC_RPC_URL}"
bsc = "${BNB_RPC_URL}"
avalanche = "${AVALANCHE_RPC_URL}"
arbitrum = "${ARBITRUM_RPC_URL}"
optimism = "${OPTIMISM_RPC_URL}"
base = "${BASE_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
katana = "${KATANA_RPC_URL}"
katanabokuto = "${KATANA_BOKUTO_RPC_URL}"
plume = "${PLUME_MAINNET_RPC_URL}"
soneium = "${SONEIUM_RPC_URL}"

[etherscan]
mainnet = { key = "${ETHEREUM_KEY}", url = "https://api.etherscan.io/api" }
# polygon = { key = "${POLYGONSCAN_KEY}" }
# bsc = { key = "${BSCSCAN_KEY}" }
# avalanche = { key = "${SNOWTRACE_KEY}" }
arbitrum = { key = "${ARBISCAN_KEY}", chain = 42161, url = "https://api.etherscan.io/v2/api" }
optimism = { key = "${OPTIMISMSCAN_KEY}", chain = 10, url = "https://api.etherscan.io/v2/api?chainid=10" }
# base = { key = "${BASESCAN_KEY}" }
# sepolia = { key = "${SEPOLIA_KEY}", chain = 11155111, url = "https://api.etherscan.io/v2/api" }
sepolia = { key = "${SEPOLIA_KEY}", chain = 11155111, url = "https://api.etherscan.io/v2/api?chainid=11155111" }
katana = { key = "${KATANA_KEY}", chain = 747474, url = "https://explorer.katanarpc.com/api" }
katanabokuto = { key = "${KATANA_BOKUTO_KEY}", chain = 737373, url = "https://explorer-bokuto.katanarpc.com/api" }
soneium = { key = "${SONEIUM_KEY}", chain = 1868, url = "https://soneium.blockscout.com/api" }

[fmt]
FOUNDRY_FMT_LINE_LENGTH = 120
FOUNDRY_FMT_TAB_WIDTH = 4
FOUNDRY_FMT_BRACKET_SPACING = true
FOUNDRY_FMT_INT_TYPES = "long"
FOUNDRY_FMT_MULTILINE_FUNC_HEADER = "attributes_first"
FOUNDRY_FMT_QUOTE_STYLE = "double"
FOUNDRY_FMT_NUMBER_UNDERSCORE = "thousands"
FOUNDRY_FMT_OVERRIDE_SPACING = true
FOUNDRY_FMT_WRAP_COMMENTS = false
FOUNDRY_FMT_IGNORE = []
